### ISSUE TITLE
Allow scripts to be disabled

### ISSUE THREAD

**Issue by ericduran** [Lullabot/lubot#16]
right now everything under script is automatically added.

This was a hassle for me since I didn't want the github integration :-/ had to remove the file.

Super low priority.

**Comment by justafish** [comment]
How about a .js file that exports an object in CommonJS style? e.g. https://github.com/Lullabot/lullabot.com-www/blob/master/settings.js

**Comment by ericduran** [comment]
How about yml?

Just like the config.json except it'll have comment support and simpler than json.

We do something similar in our pubstack:

``` yml
synced_folder: ~/Sites/nbcu

memory: 2048
cpus: 2

sites:
- subscription: nbcupublisher7
  shortname: nbcupublisher7 
  vhost:
    servername: local.publisher7.com
    documentroot: Publisher7/docroot
- subscription: nbcunbc
  shortname: nbcunbc
  vhost:
    servername: local.nbc.com
    documentroot: Publisher7_nbc/docroot

config:
  nodejs: true
  phantomjs: true
  ruby: true
  splunk: true
```
